[package]
name = "rmachine-mos6502"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
clap-num = "1.2.0"
rmachine-core = { path = "../rmachine-core" }

[lints]
workspace = true
